name: max_lines_function_lint
description: Check that your function don't exceed a maximum of lines
version: 1.0.3
repository: https://github.com/emilefournout/max_lines_function_lint
screenshots:
 - description: 'Examples of lint'
   path: screenshots/screenshot.png

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  analyzer: ">=6.0.0 <7.0.0"
  custom_lint_builder: ^0.5.12
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
